// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package ports

const (
	Admin_authorizerScopes = "admin_authorizer.Scopes"
)

// AdminPost defines model for AdminPost.
type AdminPost struct {
	Body         *string    `json:"body,omitempty"`
	CreationDate *int64     `json:"creationDate,omitempty"`
	Draft        *PostDraft `json:"draft,omitempty"`
	Slug         *string    `json:"slug,omitempty"`
	Title        *string    `json:"title,omitempty"`
}

// NewPostRequest defines model for NewPostRequest.
type NewPostRequest struct {
	Body  *string `json:"body,omitempty"`
	Title *string `json:"title,omitempty"`
}

// Post defines model for Post.
type Post struct {
	Body         *string `json:"body,omitempty"`
	CreationDate *int64  `json:"creationDate,omitempty"`
	Slug         *string `json:"slug,omitempty"`
	Title        *string `json:"title,omitempty"`
}

// PostDraft defines model for PostDraft.
type PostDraft struct {
	Body  *string `json:"body,omitempty"`
	Title *string `json:"title,omitempty"`
}

// UpdatePostRequest defines model for UpdatePostRequest.
type UpdatePostRequest struct {
	Body  *string `json:"body,omitempty"`
	Title *string `json:"title,omitempty"`
}

// PostApiV1AdminPostsJSONRequestBody defines body for PostApiV1AdminPosts for application/json ContentType.
type PostApiV1AdminPostsJSONRequestBody = NewPostRequest

// PutApiV1AdminPostsPostSlugJSONRequestBody defines body for PutApiV1AdminPostsPostSlug for application/json ContentType.
type PutApiV1AdminPostsPostSlugJSONRequestBody = UpdatePostRequest
